name: Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: '17 7 * * 0'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - run: ./build-and-test.cmd
